
package service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AlumnoService", targetNamespace = "http://api.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlumnoService {


    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosPersonales
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosPersonales", targetNamespace = "http://api.service/", className = "service.api.GetDatosPersonales")
    @ResponseWrapper(localName = "getDatosPersonalesResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosPersonalesResponse")
    public DatosPersonales getDatosPersonales(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosPrincipales
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosPrincipales", targetNamespace = "http://api.service/", className = "service.api.GetDatosPrincipales")
    @ResponseWrapper(localName = "getDatosPrincipalesResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosPrincipalesResponse")
    public DatosPrincipales getDatosPrincipales(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosDomicilio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosDomicilio", targetNamespace = "http://api.service/", className = "service.api.GetDatosDomicilio")
    @ResponseWrapper(localName = "getDatosDomicilioResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosDomicilioResponse")
    public DatosDomicilio getDatosDomicilio(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosFamiliares
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosFamiliares", targetNamespace = "http://api.service/", className = "service.api.GetDatosFamiliares")
    @ResponseWrapper(localName = "getDatosFamiliaresResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosFamiliaresResponse")
    public DatosFamiliares getDatosFamiliares(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosExtranjeros
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosExtranjeros", targetNamespace = "http://api.service/", className = "service.api.GetDatosExtranjeros")
    @ResponseWrapper(localName = "getDatosExtranjerosResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosExtranjerosResponse")
    public DatosExtranjeros getDatosExtranjeros(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosFormacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosFormacion", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacion")
    @ResponseWrapper(localName = "getDatosFormacionResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacionResponse")
    public DatosFormacion getDatosFormacion(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosFormacionSecundaria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosFormacionSecundaria", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacionSecundaria")
    @ResponseWrapper(localName = "getDatosFormacionSecundariaResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacionSecundariaResponse")
    public DatosFormacionSecundaria getDatosFormacionSecundaria(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosFormacionSuperior
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosFormacionSuperior", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacionSuperior")
    @ResponseWrapper(localName = "getDatosFormacionSuperiorResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosFormacionSuperiorResponse")
    public DatosFormacionSuperior getDatosFormacionSuperior(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosSocioEconomicos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosSocioEconomicos", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicos")
    @ResponseWrapper(localName = "getDatosSocioEconomicosResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosResponse")
    public DatosSocioEconomicos getDatosSocioEconomicos(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosSocioEconomicosGenerales
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosSocioEconomicosGenerales", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosGenerales")
    @ResponseWrapper(localName = "getDatosSocioEconomicosGeneralesResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosGeneralesResponse")
    public DatosSocioEconomicosGenerales getDatosSocioEconomicosGenerales(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosSocioEconomicosSalud
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosSocioEconomicosSalud", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSalud")
    @ResponseWrapper(localName = "getDatosSocioEconomicosSaludResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSaludResponse")
    public DatosSocioEconomicosSalud getDatosSocioEconomicosSalud(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosSocioEconomicosSituacionLaboralPadres
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosSocioEconomicosSituacionLaboralPadres", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSituacionLaboralPadres")
    @ResponseWrapper(localName = "getDatosSocioEconomicosSituacionLaboralPadresResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSituacionLaboralPadresResponse")
    public DatosSocioEconomicosSituacionLaboralPadres getDatosSocioEconomicosSituacionLaboralPadres(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosSocioEconomicosSituacionLaboralPersonal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosSocioEconomicosSituacionLaboralPersonal", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSituacionLaboralPersonal")
    @ResponseWrapper(localName = "getDatosSocioEconomicosSituacionLaboralPersonalResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosSocioEconomicosSituacionLaboralPersonalResponse")
    public DatosSocioEconomicosSituacionLaboralPersonal getDatosSocioEconomicosSituacionLaboralPersonal(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

    /**
     * 
     * @param dniAlumno
     * @return
     *     returns service.api.DatosCondicionAcademica
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosCondicionAcademica", targetNamespace = "http://api.service/", className = "service.api.GetDatosCondicionAcademica")
    @ResponseWrapper(localName = "getDatosCondicionAcademicaResponse", targetNamespace = "http://api.service/", className = "service.api.GetDatosCondicionAcademicaResponse")
    public DatosCondicionAcademica getDatosCondicionAcademica(
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno);

}
